version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platform
    volumes:
      - ./:/app
    ports:
      - "8087:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://lochinbek:lochin@db:5432/platform

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: lochinbek
      POSTGRES_PASSWORD: lochin
      POSTGRES_DB: platform
    container_name: platform_postgres
    ports:
      - "5433:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lochinbek -d platform"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  psql_data:  # Named volume for PostgreSQL data
